version: '3'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: notes_app
      MYSQL_ROOT_PASSWORD: callicoder
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=callicoder--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  java:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "80:80"